

gc = {
	'da pele': 'beje',
	'beje': 'beje',
	'caramelo': 'beje',
	'azul': 'azul',
	'azui': 'azul',
	'azuis': 'azul',
	'azulão': 'azul',
	'azulado': 'azul',
	'azulzado': 'azul',
	'azulsado': 'azul',
	'azulzadu': 'azul',
	'azulsadu': 'azul',
	'azuzado': 'azul',
	'azusado': 'azul',
	'azulaum': 'azul',
	'azulzão': 'azul',
	'azulzarão': 'azul',
	'azulzarrão': 'azul',
	'azule': 'azul',
	'asul': 'azul',
	'asulão': 'azul',
	'asulaum': 'azul',
	'azur': 'azul',
	'azulzin': 'azul',
	'azulsinho': 'azul',
	'azulzinho': 'azul',
	'azuzin': 'azul',
	'azuzim': 'azul',
	'azusim': 'azul',
	'azuzinho': 'azul',
	'azuzinhu': 'azul',
	'asusinho': 'azul',
	'asusinho': 'azul',
	'azul escuro': 'azul',
	'azul claro': 'azul',
	'azul marinho': 'azul',
	'vermelho': 'vermelho',
	'vermelha': 'vermelho',
	'vermelho escuro': 'vermelho',
	'vermelha escura': 'vermelho',
	'vermelho claro': 'vermelho',
	'vermelha clara': 'vermelho',
	'vermelhinho': 'vermelho',
	'vermelhozinho': 'vermelho',
	'vermelhozin': 'vermelho',
	'vermelhinha': 'vermelho',
	'vermelhazinha': 'vermelho',
	'vermelhão': 'vermelho',
	'vermelhona': 'vermelho',
	'avermelhado': 'vermelho',
	'avermelhadão': 'vermelho',
	'vermelhozão': 'vermelho',
	'vermelhinhozinho': 'vermelho',
	'vermelhinhozinhu': 'vermelho',
	'vermei': 'vermelho',
	'vermeim': 'vermelho',
	'vermeizim': 'vermelho',
	'vermeizinho': 'vermelho',
	'vermeizinha': 'vermelho',
	'vermei escuro': 'vermelho',
	'vermeim escuro': 'vermelho',
	'vermeizim  escuro': 'vermelho',
	'vermeizinho escuro': 'vermelho',
	'vermeizinha escuro': 'vermelho',
	'vermei claro': 'vermelho',
	'vermeim claro': 'vermelho',
	'vermeizim  claro': 'vermelho',
	'vermeizinho claro': 'vermelho',
	'vermeizinha claro': 'vermelho',
	'vermei clara': 'vermelho',
	'vermeim clara': 'vermelho',
	'vermeizim  clara': 'vermelho',
	'vermeizinho clara': 'vermelho',
	'vermeizinha clara': 'vermelho',
	'avermelhadinho': 'vermelho',
	'avermelhadim': 'vermelho',
	'avermelhadão': 'vermelho',
	'vermeião': 'vermelho',
	'vermeiona': 'vermelho',
	'vermeiaço': 'vermelho',
	'vermeizão': 'vermelho',
	'vermeisão': 'vermelho',
	'vermeilhão': 'vermelho',
	'vermeilhim': 'vermelho',
	'vermeilhinho': 'vermelho',
	'amarelo': 'amarelo',
	'amarela': 'amarelo',
	'amarelo escuro': 'amarelo',
	'amarela escura': 'amarelo',
	'amarela escuro': 'amarelo',
	'amarelo claro': 'amarelo',
	'amarela clara': 'amarelo',
	'amarela claro': 'amarelo',
	'amarelim': 'amarelo',
	'amarelin': 'amarelo',
	'amarelinho': 'amarelo',
	'amarelinha': 'amarelo',
	'amarelozim': 'amarelo',
	'amarelozinho': 'amarelo',
	'amarelão': 'amarelo',
	'amarelaço': 'amarelo',
	'amareladão': 'amarelo',
	'amarelozarrão': 'amarelo',
	'amarelozarão': 'amarelo',
	'amarelado': 'amarelo',
	'amareladinho': 'amarelo',
	'amareladaço': 'amarelo',
	'marelo': 'amarelo',
	'marelin': 'amarelo',
	'marelinho': 'amarelo',
	'marelin claro': 'amarelo',
	'marelinho claro': 'amarelo',
	'marelim': 'amarelo',
	'marelado': 'amarelo',
	'marelão': 'amarelo',
	'malelo': 'amarelo',
	'amalero': 'amarelo',
	'malero': 'amarelo',
	'amalelo': 'amarelo',
	'malero': 'amarelo',
	'malelo': 'amarelo',
	'malelinho': 'amarelo',
	'malelim': 'amarelo',
	'malerim': 'amarelo',
	'malerinho': 'amarelo',
	'verde': 'verde',
	'verda': 'verde',
	'verdim': 'verde',
	'verdinho': 'verde',
	'verdin': 'verde',
	'verdão': 'verde',
	'verde claro': 'verde',
	'verda claro': 'verde',
	'verdim claro': 'verde',
	'verdinho claro': 'verde',
	'verdin claro': 'verde',
	'verdão claro': 'verde',
	'verde escuro': 'verde',
	'verda escuro': 'verde',
	'verdim escuro': 'verde',
	'verdinho escuro': 'verde',
	'verdin escuro': 'verde',
	'verdão escuro': 'verde',
	'verdezão': 'verde',
	'verdaço': 'verde',
	'verdasso': 'verde',
	'verdezinho': 'verde',
	'verdesinho': 'verde',
	'verdezinhu': 'verde',
	'verdesinhu': 'verde',
	'verdinzão': 'verde',
	'verdinsão': 'verde',
	'verdinzinho': 'verde',
	'verdinsinho': 'verde',
	'verdinzinhu': 'verde',
	'verdinsinhu': 'verde',
	'verdezado': 'verde',
	'verdesado': 'verde',
	'averdesado': 'verde',
	'averdezado': 'verde',
	'averdado': 'verde',
	'verdeado': 'verde',
	'averdeado': 'verde',
	'esverdeado': 'verde',
	'isverdeado': 'verde',
	'isverdeadu': 'verde',
	'esverdiado': 'verde',
	'esverdiadão': 'verde',
	'isverdiadão': 'verde',
	'isverdiado': 'verde',
	'isverdiadu': 'verde',
	'isverdeadaum': 'verde',
	'isverdeazão': 'verde',
	'rosa':'rosa',
	'roza':'rosa',
	'rose':'rosa',
	'rosin':'rosa',
	'rosinha':'rosa',
	'rosim':'rosa',
	'rosadim':'rosa',
	'rosadin':'rosa',
	'rosão':'rosa',
	'rozão':'rosa',
	'rosaum':'rosa',
	'rosa escuro':'rosa',
	'roza escuro':'rosa',
	'rose escuro':'rosa',
	'rosin escuro':'rosa',
	'rosinha escuro':'rosa',
	'rosim escuro':'rosa',
	'rosadim escuro':'rosa',
	'rosadin escuro':'rosa',
	'rosão escuro':'rosa',
	'rozão escuro':'rosa',
	'rosaum escuro':'rosa',
	'rosa claro':'rosa',
	'roza claro':'rosa',
	'rose claro':'rosa',
	'rosin claro':'rosa',
	'rosinha claro':'rosa',
	'rosim claro':'rosa',
	'rosadim claro':'rosa',
	'rosadin claro':'rosa',
	'rosão claro':'rosa',
	'rozão claro':'rosa',
	'rosaum claro':'rosa',
	'arosinhadim':'rosa',
	'arosinhado':'rosa',
	'arosado':'rosa',
	'arosadim':'rosa',
	'arosadin':'rosa',
	'arrosinhadim':'rosa',
	'arrosinhado':'rosa',
	'arrosado':'rosa',
	'arrosadim':'rosa',
	'arrosadin':'rosa',
	'rosadinha':'rosa',
	'rozinha':'rosa',
	'rosado':'rosa',
	'rosada':'rosa',
	'rozado':'rosa',
	'rozada':'rosa',
	'roseada':'rosa',
	'roseado':'rosa',
	'rrosa':'rosa',
	'rosadona':'rosa',
	'rosadão':'rosa',
	'rosadaço':'rosa',
	'rosadaça':'rosa',
	'arosado':'rosa',
	'arosada':'rosa',
	'arozado':'rosa',
	'arozada':'rosa',
	'aroseada':'rosa',
	'aroseado':'rosa',
	'arrosado':'rosa',
	'arrosada':'rosa',
	'arrozado':'rosa',
	'arrozada':'rosa',
	'arroseada':'rosa',
	'arroseado':'rosa',
	'preto': 'preto',
	'preta': 'preto',
	'pretim': 'preto',
	'pretão': 'preto',
	'pretaço': 'preto',
	'pretaum': 'preto',
	'pretinha': 'preto',
	'preto fosco': 'preto',
	'preta fosco': 'preto',
	'pretim fosco': 'preto',
	'pretão fosco': 'preto',
	'pretaço fosco': 'preto',
	'pretaum fosco': 'preto',
	'pretinha fosco': 'preto',
	'pretinha fosco': 'preto',
	'preto fosca': 'preto',
	'preta fosca': 'preto',
	'pretim fosca': 'preto',
	'pretão fosca': 'preto',
	'pretaço fosca': 'preto',
	'pretaum fosca': 'preto',
	'pretinha fosca': 'preto',
	'pretinho fosca': 'preto',
	'preto brilhante': 'preto',
	'preta brilhante': 'preto',
	'pretim brilhante': 'preto',
	'pretão brilhante': 'preto',
	'pretaço brilhante': 'preto',
	'pretaum brilhante': 'preto',
	'pretinha brilhante': 'preto',
	'pretinho brilhante': 'preto',
	'pretinhazinha': 'preto',
	'pretozado': 'preto',
	'pretinho': 'preto',
	'pretinhazinho': 'preto',
	'pretozada': 'preto',
	'branco': 'branco',
	'branca': 'branco',
	'branquim': 'branco',
	'branquin': 'branco',
	'branquinha': 'branco',
	'branquinho': 'branco',
	'branco fosco': 'branco',
	'branca fosco': 'branco',
	'branquim fosco': 'branco',
	'branquin fosco': 'branco',
	'branquinha fosco': 'branco',
	'branquinho fosco': 'branco',
	'branco fosca': 'branco',
	'branca fosca': 'branco',
	'branquim fosca': 'branco',
	'branquin fosca': 'branco',
	'branquinha fosca': 'branco',
	'branquinho fosca': 'branco',
	'branco brilhante': 'branco',
	'branca brilhante': 'branco',
	'branquim brilhante': 'branco',
	'branquin brilhante': 'branco',
	'branquinha brilhante': 'branco',
	'branquinho brilhante': 'branco',
	'branquinhão': 'branco',
	'brancão': 'branco',
	'brancaço': 'branco',
	'esbranqueado': 'branco',
	'lilas': 'lilás',
	'lilás': 'lilás',
	'lila': 'lilás',
	'lilá': 'lilás',
	'lilai': 'lilás',
	'lilái': 'lilás',
	'lilase': 'lilás',
	'lilases': 'lilás',
	'lilaze': 'lilás',
	'liláse': 'lilás',
	'liláses': 'lilás',
	'liláze': 'lilás',
	'lilasinho': 'lilás',
	'lilasão': 'lilás',
	'lilazão': 'lilás',
	'lilaisinho': 'lilás',
	'lilaisão': 'lilás',
	'lilaizão': 'lilás',
	'roxo': 'roxo',
	'rouxo': 'roxo',
	'roxu': 'roxo',
	'rouxo': 'roxo',
	'roxin': 'roxo',
	'roxim': 'roxo',
	'roxinho': 'roxo',
	'rouxim': 'roxo',
	'rouxinho': 'roxo',
	'roxa': 'roxo',
	'rouxa': 'roxo',
	'aroxadinha': 'roxo',
	'rouxona': 'roxo',
	'roxinha': 'roxo',
	'roxi': 'roxo',
	'roxão': 'roxo',
	'roxao': 'roxo',
	'roxaum': 'roxo',
	'rouxão': 'roxo',
	'rocho': 'roxo',
	'rochão': 'roxo',
	'rochinho': 'roxo',
	'rochim': 'roxo',
	'rochin': 'roxo',
	'rochim': 'roxo',
	'aroxeado': 'roxo',
	'aroxado': 'roxo',
	'arouxeado': 'roxo',
	'violeta': 'violeta',
	'violetinha': 'violeta',
	'violetim': 'violeta',
	'violetão': 'violeta',
	'violetaço': 'violeta',
	'marron': 'marron',
	'maron': 'marron',
	'marronzin': 'marron',
	'marronsin': 'marron',
	'marronzinho': 'marron',
	'marronzinha': 'marron',
	'marronsinha': 'marron',
	'marronsão': 'marron',
	'marronzão': 'marron',
	'marronzaço': 'marron',
	'maronsin': 'marron',
	'maronzin': 'marron',
	'maronzinho': 'marron',
	'maronzinha': 'marron',
	'maronsinha': 'marron',
	'maronsão': 'marron',
	'maronzão': 'marron',
	'maronzaço': 'marron',
	'cinza': 'cinza',
	'acinzentado': 'cinza',
	'acinzentada': 'cinza',
	'cinsa': 'cinza',
	'sinza': 'cinza',
	'sinsa': 'cinza',
	'cinzinha': 'cinza',
	'cinzinho': 'cinza',
	'cinzão': 'cinza'	
	}
	

	