 
gt = {
    'cerveja': 'bebidas',
	'cerva': 'bebidas',
    'agua com ga': 'bebidas',
	'agua': 'bebidas',
    'bebidas': 'bebidas',
    'pinga': 'bebidas',
    'guarana': 'bebidas',
    'vinho': 'bebidas',
    'whisky': 'bebidas',
    'panela': 'produtos de cozinha',
    'aquario': 'produtos de pet shop',
	'aquario de peixe': 'produtos de pet shop',
    'carne': 'alimentos',
    'arroz': 'alimentos',
    'feijao': 'alimentos',
	'feijoe': 'alimentos',
	'feijao preto': 'alimentos',
	'feijoe preto': 'alimentos',
    'roupa': 'vestuário', 
    'relogio': 'acessórios', 
    'bijouteria': 'acessórios de moda', 
    'calcado': 'calçados', 
    'movei': 'mobiliário', 
	'movei fino': 'mobiliário', 
    'eletrodoméstico': 'eletrodomésticos', 
    'eletronico': 'eletrônicos', 
    'smartphone': 'smartphones', 
    'credito de telefone': 'créditos para celular',
	'credito de celular': 'créditos para celular',
	'credito em telefone': 'créditos para celular',
	'credito no telefone': 'créditos para celular',
	'credito para telefone': 'créditos para celular',
	'credito em celular': 'créditos para celular',
	'credito no celular': 'créditos para celular',
	'credito para celular': 'créditos para celular',
	'celular': 'celulares', 
    'barraca': 'artigos de camping', 
    'mexirica': 'alimentos', 
    'cintos': 'vestuário', 
    'fruta': 'alimentos', 
    'barbeador': 'artigos de higiene pessoal',
    'prestobarba': 'artigos de higiene pessoal', 
    'lampada': 'iluminação',
	'lampida': 'iluminação',
	'lamparina': 'iluminação',
	'luminaria': 'iluminação',
    'tomada': 'artigos para eletricistas', 
    'chuveiro': 'artigos para eletricistas',
	'torneira': 'artigos para encanadores',
    'cabide': 'acessórios para vestuário', 
    'ar condicionado': 'eletrodomésticos', 
    'micro-ondas': 'eletrodomésticos', 
    'copo descartável': 'artigos descartáveis', 
    'colheres': 'artigos de cozinha',
    'garfo': 'artigos de cozinha', 
    'faca': 'artigos de cozinha', 
    'pilha': 'acessórios para eletrônicos', 
    'bateria de celular': 'acessórios para celular', 
    'bateria': 'acessórios para eletrônicos', 
    'capa': 'acessórios diversos', 
    'capas': 'acessórios diversos', 
    'capinha': 'acessórios diversos', 
    'cabo': 'acessórios diversos', 
    'carregador': 'acessórios diversos', 
    'carregador veicular': 'acessórios para celular', 
    'taca': 'artigos de cozinha', 
    'lixeira': 'artigos domésticos', 
    'vasilhas': 'artigos domésticos', 
    'vasilha': 'artigos domésticos', 
    'recipiente': 'artigos domésticos',
    'prendedor': 'artigos domésticos',
    'livro': 'artigos de literatura', 
    'notebook': 'computadores', 
    'laptop': 'computadores', 
	'computadore': 'computadores', 
	'computador': 'computadores', 
    'geladeira': 'eletrodomésticos', 
    'ventilador': 'eletrodomésticos', 
    'forno': 'eletrodomésticos', 
    'roda': 'acessórios', 
    'lanterna': 'acessórios', 
    'relogio': 'acessórios', 
    'refrigerante': 'bebidas', 
    'garrafa': 'garrafas', 
    'cama': 'cama, mesa e banho', 
    'colchao': 'cama, mesa e banho', 
    'travesseiro': 'cama, mesa e banho', 
    'colcha': 'cama, mesa e banho', 
    'tablet': 'eletrônicos', 
    'camera': 'eletrônicos', 
    'toalha': 'cama, mesa e banho', 
    'limpador': 'produtos de limpeza', 
    'detergente': 'produtos de limpeza', 
    'remedio': 'remedios', 
	'medicamento': 'medicamentos', 
    'sabao': 'produtos de limpeza', 
    'sabao em po': 'produtos de limpeza', 
    'bolsinha': 'acessórios', 
    'polchete': 'acessórios', 
    'oculos de sol': 'acessórios', 
    'bone': 'acessórios', 
    'camisa': 'vestuário', 
    'camiseta': 'vestuário', 
    'calça': 'vestuário', 
    'bermuda': 'vestuário', 
    'jeans': 'vestuário', 
    'cobertor': 'cama, mesa e banho', 
    'memoria': 'peças de computador', 
    'processador': 'peças de computador', 
    'tv Led': 'eletrodomésticos', 
    'impressora': 'informática', 
    'sutia': 'vestuário', 
    'calcinha': 'vestuário', 
    'cueca': 'vestuário', 
    'sunga': 'vestuário', 
    'gravata': 'vestuário', 
    'roteador wi-fi': 'informática', 
    'maquiagem': 'produtos de beleza', 
    'chinelo': 'calçados', 
    'havainas': 'calçados', 
    'fone de ouvido': 'acessórios', 
    'macarrao': 'alimentos', 
    'batata frita': 'alimentos', 
    'abobora': 'alimentos', 
    'lencol casal': 'cama, mesa e banho', 
    'sanduiche': 'alimentos', 
    'armario': 'mobiliário', 
    'armarinho': 'mobiliário', 
    'racao': 'produtos de pet shop', 
    'refeicao': 'alimentos', 
    'semente': 'produtos para plantio', 
    'linguiça': 'alimentos', 
    'ventoinha': 'peças', 
    'xicara': 'artigos de cozinha', 
    'mouse': 'informática', 
    'teclado': 'informática', 
    'telinha': 'peças',
    'medidor de pressão': 'acessórios de saúde', 
    'dosador': 'acessórios', 
    'cortador': 'acessórios', 
    'cadeira': 'mobiliário', 
    'banqueta': 'mobiliário', 
    'balde': 'artigos domésticos', 
    'bacia': 'artigos domésticos', 
    'vazo': 'artigos domésticos', 
    'vazo de flor': 'artigos domésticos', 
    'cimento': 'artigos de construção civil', 
    'tijolo': 'artigos de construção civil', 
    'telha': 'artigos de construção civil', 
    'carvao': 'artigos para churrasco', 
    'camarao': 'alimentos', 
    'espelho': 'acessórios', 
    'espeto': 'artigos para churrasco', 
    'roldana': 'peças', 
    'rodinha': 'peças', 
    'pneu': 'peças', 
    'bicicleta': 'produtos do ciclismo', 
    'capacete': 'acessórios', 
    'tenis': 'calçados', 
    'sapatilha': 'calçados', 
    'sapatenis': 'calçados', 
    'lasanha': 'alimentos', 
    'pizza': 'alimentos', 
    'oleo': 'alimentos', 
    'cotonete': 'artigos de higiene pessoal', 
    'colchonete': 'cama, mesa e banho', 
    'coraçao de galinha': 'alimentos', 
    'bacon': 'alimentos', 
    'agriao': 'alimentos', 
    'perfume': 'perfumaria', 
    'desodorante': 'artigos de higiene pessoal', 
    'pasta de dente': 'artigos de higiene pessoal', 
    'sabonete': 'artigos de higiene pessoal', 
    'Cd': 'discos', 
    'dvd': 'discos', 
    'selo': 'artigos do correio', 
    'super bonder': 'produtos diversos', 
    'coca': 'bebidas', 
    'fanta': 'bebidas', 
    'suco': 'bebidas', 
    'vodka': 'bebidas', 
    'radio': 'eletrônicos', 
    'foninho': 'acessórios', 
    'reator': 'peças', 
    'conversor': 'acessórios', 
    'butina': 'calçados', 
    'sandalia': 'calçados', 
    'copo': 'artigos de cozinha', 
    'panela de pressão': 'artigos de cozinha', 
    'fechadura': 'artigos de chaveiros', 
    'chave philips': 'ferramentas', 
    'chave': 'ferramentas', 
    'chave de fenda': 'ferramentas', 
    'sifao': 'artigos de construção civil', 
    'ralo': 'artigos de construção civil', 
    'porca': 'peças', 
    'parafuso': 'peças', 
    'porta trecos': 'acessórios', 
    'anel': 'acessórios', 
    'brinco': 'acessórios de beleza', 
    'esmalte': 'maquiagem', 
    'maquiagem': 'cosméticos', 
    'manequim': 'acessórios para vestuário', 
    'blushe': 'maquiagem', 
    'blusa': 'vestuário', 
    'moletom': 'vestuário', 
    'ovos': 'alimentos', 
    'fonte': 'peças', 
    'coelho': 'animais', 
    'fio': 'artigos para eletricistas', 
    'cigarro': 'tabacaria', 
    'palheiro': 'tabacaria', 
	'panheiro': 'tabacaria', 
    'calcio': 'suplementos', 
    'vitamina': 'suplementos', 
    'analgesico': 'medicamentos', 
	'analgezico': 'medicamentos', 
    'remedio pra gripe': 'medicamentos', 
	'remedio pra toce': 'medicamentos', 
	'remedio para gripe': 'medicamentos', 
	'remedio para toce': 'medicamentos', 
    'vacina': 'vacinas', 
    'nicho': 'mobiliário', 
    'estante': 'mobiliário', 
    'bancada': 'mobiliário', 
    'guarda roupas': 'mobiliário', 
    'chapeu': 'acessórios', 
    'serpentinha': 'peças', 
    'palmito': 'alimentos', 
    'feijoada': 'alimentos', 
    'salshicha': 'alimentos', 
    'salgado': 'alimentos', 
    'sal': 'alimentos', 
    'salame': 'alimentos', 
    'elma chip': 'alimentos', 
    'dorito': 'alimentos', 
    'fandango': 'alimentos', 
    'cheeto': 'alimentos', 
    'baconzito': 'alimentos', 
    'salada': 'alimentos', 
    'porta': 'peças', 
    'retrato': 'retratos', 
    'binóculo': 'acessórios', 
	'binoculo': 'acessórios', 
    'pente': 'acessórios', 
    'escova': 'acessórios', 
    'cortador de grama': 'eletrodomésticos', 
    'maquina de lavar': 'eletrodomésticos', 
    'forno eletrico': 'eletrodomésticos', 
    'penteadeira': 'mobiliário', 
    'talco': 'produtos de higiene', 
    'tanquinho': 'eletrodomésticos', 
    'poltrona': 'mobiliário', 
    'carimbo': 'carimbos', 
    'caixa de som': 'acessórios', 
    'pia': 'artigos para construção civil', 
    'vávula': 'peças', 
    'cedeado': 'acessórios', 
    'chaveiro': 'acessórios', 
    'argola': 'acessórios', 
    'argamassa': 'artigos para construção civil', 
    'shampoo': 'artigos de higiene pessoal', 
    'condicionador': 'artigos de higiene pessoal', 
    'fivela': 'acessórios', 
    'medidor': 'acessórios', 
    'silicone': 'acessórios', 
    'chip': 'componentes eletrônicos', 
    'guarda chuva': 'acessórios', 
    'sombrinha': 'acessórios', 
    'maçaneta': 'peças', 
    'solda': 'ferramentas', 
    'macarico': 'ferramentas', 
    'ferro de passar': 'eletrodomésticos', 
    'suporte pvc': 'peças', 
    'suporte parede': 'peças', 
	'suporte de parede': 'peças', 
	'suporte para parede': 'peças', 
    'pe': 'peças', 
    'corda': 'produtos agropecuários', 
    'bobina': 'peças', 
    'rolo': 'peças', 
    'bolo': 'alimentos', 
    'bala': 'alimentos', 
    'chiclete': 'alimentos', 
    'balinha': 'alimentos', 
    'chocolate': 'alimentos', 
    'toddy': 'alimentos', 
    'nescau': 'alimentos', 
    'cereau': 'alimentos', 
    'panqueca': 'alimentos', 
    'frigideira': 'artigos de cozinha', 
    'grill': 'eletrodomésticos', 
    'mesa': 'mobiliário', 
    'trofeu': 'acessórios', 
    'medalha': 'acessórios', 
    'diamante': 'artigos de extremo luxo', 
    'máquina de costura': 'maquinário', 
    'prendedor de roupas': 'acessórios em geral', 
    'verniz': 'produtos de uso industrial', 
    'descolorante': 'artigos de higiene', 
    'desengripante': 'artigos de uso industrial', 
    'adaptador': 'acessórios', 
    'Smart TV': 'eletrodomésticos',
	'goro': 'bebidas', 
	'manga': 'alimentos',
	'uva': 'alimentos',
	'morango': 'alimentos',
	'picanha': 'alimentos',
	'contra file': 'alimentos',
	'carne': 'alimentos',
	'pamonha': 'alimentos',
	'alcatra': 'alimentos',
	'file': 'alimentos',
	'file mignon': 'alimentos',
	'fralda': 'produtos de higiene para bebês',
	'fralda descartavel': 'produtos de higiene para bebês',
	'fralda de algodao': 'produtos de higiene para bebês',
	'fralda descartavei': 'produtos de higiene para bebês',
	'fralda para bebe': 'produtos de higiene para bebês',
	'rapadura': 'alimentos',
	'goiaba': 'alimentos',
	'abacaxi': 'alimentos',
	'tangerina': 'alimentos',
	'melancia': 'alimentos',
	'fraldinha': 'alimentos',
	'fraudinha': 'alimentos',
	'peixe': 'alimentos',
	'alface': 'alimentos',
	'legume': 'alimentos',
	'cupim': 'alimentos',
	'cereja': 'alimentos',
	'sanduba': 'alimentos',
	'bauru': 'alimentos',
	'agriao': 'alimentos',
	'rucula': 'alimentos',
	'melao': 'alimentos',
	'mel': 'alimentos',
	'melado': 'alimentos',
	'cogumelo': 'alimentos',
	'azeite': 'alimentos',
	'adocante': 'alimentos',
	'acucar': 'alimentos',
	'frita': 'alimentos',
	'churrasqueira': 'produtos para churrasco',
	'churrasquinho': 'alimentos',
	'churrasco': 'alimentos',
	'marmita': 'alimentos',
	'marmitex': 'alimentos',
	'maca': 'alimentos',
	'marmitinha': 'alimentos',
	'banana': 'alimentos',
	'bananada': 'alimentos',
	'goiabada': 'alimentos',
	'marmelada': 'alimentos',
	'coco': 'alimentos',
	'cocada': 'alimentos',
	'gilo': 'alimentos',
	'jurubeba': 'alimentos',
	'torresmo': 'alimentos',
	'toucinho': 'alimentos',
	'lingua': 'alimentos',
	'figado': 'alimentos',
	'peito de frango': 'alimentos',
	'file de peixe': 'alimentos',
	'salmao': 'alimentos',
	'file de tilapia': 'alimentos',
	'file de merlusa': 'alimentos',
	'cera': 'produtos de polimento',
	'sacola': 'embalagens',
	'sanfona': 'instrumentos musicais',
	'piano': 'instrumentos musicais',
	'viola': 'instrumentos musicais',
	'violao': 'instrumentos musicais',
	'violino': 'instrumentos musicais',
	'cx de som': 'instrumentos musicais',
	'gaita': 'instrumentos musicais',
	'flauta': 'instrumentos musicais',
	'trompete': 'instrumentos musicais',
	'trombone': 'instrumentos musicais',
	'saxofone': 'instrumentos musicais',
	'baqueta': 'instrumentos musicais',
	'banqueta': 'mobiliário',
	'banco': 'mobiliário',
	'banquinho': 'mobiliário',
	'barco': 'coisas tão grandes',
	'carro': 'coisas tão grandes',
	'aviao': 'coisas tão grandes',
	'navio': 'coisas tão grandes',
	'lancha': 'coisas tão grandes',
	'jet ski': 'coisas tão grandes',
	'jetski': 'coisas tão grandes',
	'veleiro': 'coisas tão grandes',
	'vela': 'produtos gerais',
	'sensodyne': 'produtos de higiene pessoal',
	'produto de higiene pessoal': 'produtos de higiene pessoal',
	'colgate': 'produtos de higiene pessoal',
	'rexona': 'produtos de higiene pessoal',
	'palmolive': 'produtos de higiene pessoal',
	'creme dental': 'produtos de higiene pessoal',
	'creme anti-ruga': 'cosméticos',
	'enxaguante bucal': 'produtos de higiene pessoal',
	'enchaguante bucal': 'produtos de higiene pessoal',
	'fio dental': 'produtos de higiene pessoal',
	'lucretim': 'produtos de higiene íntima',
	'absorvente': 'produtos de higiene íntima',
	'tampax': 'produtos de higiene íntima',
	'costela': 'alimentos',
	'costela de vaca': 'alimentos',
	'costelinha': 'alimentos',
	'sazon': 'alimentos',
	'arisco': 'alimentos',
	'ketchup': 'alimentos',
	'maionese': 'alimentos',
	'listerine': 'produtos de higiene pessoal',
	'mostarda': 'alimentos',
	'queijo': 'alimentos',
	'mussarela': 'alimentos',
	'musarela': 'alimentos',
	'mucarela': 'alimentos',
	'molho': 'alimentos',
	'tomate': 'alimentos',
	'manjeiricao': 'alimentos',
	'manjericao': 'alimentos',
	'salsa': 'alimentos',
	'salsinha': 'alimentos',
	'cebola': 'alimentos',
	'cebolinha': 'alimentos',
	'margarita': 'bebidas',
	'margarina': 'alimentos',
	'manteiga': 'alimentos',
	'pao': 'alimentos',
	'bolacha': 'alimentos',
	'biscoito': 'alimentos',
	'brigadeiro': 'alimentos',
	'birinight': 'bebidas',
	'ice': 'bebidas',
	'campary': 'bebidas',
	'garapa': 'bebidas',
	'energetico': 'bebidas',
	'red bull': 'bebidas',
	'51 ice': 'bebidas',
	'pinga 51': 'bebidas',
	'corote': 'bebidas',
	'korote': 'bebidas',
	'karote': 'bebidas',
	'refri': 'bebidas',
	'gelo': 'produtos para bebidas',
	'gelol': 'medicamentos',
	'caracu': 'bebidas',
	'skol': 'bebidas',
	'brahma': 'bebidas',
	'antartica': 'bebidas',
	'antarctica': 'bebidas',
	'bohemia': 'bebidas',
	'itaipava': 'bebidas',
	'bavaria': 'bebidas',
	'sukita': 'bebidas',
	'kuat': 'bebidas',
	'refresco': 'bebidas',
	'suquinho': 'bebidas',
	'cafe': 'bebidas',
	'cafe em po': 'alimentos',
	'filtro de cafe': 'produtos para café',
	'filtro': 'produtos assim',
	'nescafe': 'alimentos',
	'bombom': 'alimentos',
	'bombons': 'alimentos',
	'sonho de valsa': 'alimentos',
	'lacta': 'alimentos',
	'leite': 'alimentos',
	'iogurte': 'alimentos',
	'vatapa': 'alimentos',
	'creme de leite': 'alimentos',
	'leite condensado': 'alimentos',
	'capim': 'gramíneos',
	'aspirador': 'eletrodomésticos',
	'aspirador de po': 'eletrodomésticos',
	'mocoto': 'alimentos',
	'caldo': 'alimentos',
	'pastel': 'alimentos',
	'acaraje': 'alimentos',
	'bolinho': 'alimentos',
	'bolinho frito': 'alimentos',
	'petisco': 'alimentos',
	'tira gosto': 'alimentos',
	'abobrinha': 'alimentos',
	'beterraba': 'alimentos',
	'cenoura': 'alimentos',
	'porco': 'alimentos',
	'gato': 'animais',
	'cachorro': 'animais',
	'gata': 'animais',
	'cachorra': 'animais',
	'cabra': 'animais',
	'cobra': 'animais',
	'rato': 'animais',
	'galinha': 'alimentos',
	'papa gaio': 'animais',
	'canarinho': 'animais',
	'pato': 'animais',
	'pata': 'animais',
	'ganso': 'animais',
	'gansa': 'animais',
	'panceta': 'alimentos',
	'codorna': 'animais',
	'skiny': 'alimentos',
	'mico': 'alimentos',
	'milkshake': 'alimentos',
	'milk shake': 'alimentos',
	'sorvete': 'alimentos',
	'picole': 'alimentos',
	'sunday': 'alimentos',
	'rocambole': 'alimentos',
	'sonho': 'alimentos',
	'kindin': 'alimentos',
	'quindin': 'alimentos',
	'caju': 'alimentos',
	'cajuzinho': 'alimentos',
	'cajusinho': 'alimentos',
	'castanha': 'alimentos',
	'amendoa': 'alimentos',
	'amendoim': 'alimentos',
	'torta': 'alimentos',
	'enrroladinho': 'alimentos',
	'coxinha': 'alimentos',
	'quibe': 'alimentos',
	'empada': 'alimentos',
	'emapadao': 'alimentos',
	'empanado': 'alimentos',
	'asinha': 'alimentos',
	'pastelao': 'alimentos',
	'cachorro quente': 'alimentos',
	'hotdog': 'alimentos',
	'hot dog': 'alimentos',
	'balao': 'artigos para festa',
	'baloe': 'artigos para festa',
	'camisinha': 'preservativos',
	'preservativo': 'anti-concepcionais',
	'pasta dental': 'produtos de higiene pessoais',
	'pasta dental infantil': 'produtos de higiene pessoais',
	'pasta de dente infantil': 'produtos de higiene pessoais',
	'creme dental infantil': 'produtos de higiene pessoais'
	
	}